% Robotics project, Menolotto Mariangela & Stefano Maugeri
function H = Hkalman(alpha,phi,theta,thetadot,xdotdot,ydotdot)
%HKALMAN
%    H = HKALMAN(ALPHA,PHI,THETA,THETADOT,XDOTDOT,YDOTDOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Mar-2022 11:31:38

t2 = cos(alpha);
t3 = cos(phi);
t4 = sin(alpha);
t5 = cos(theta);
t6 = sin(phi);
t7 = sin(theta);
t8 = t2.*1.0851e-2;
t9 = t4.*1.0851e-2;
t10 = t2.*3.92423e-1;
t11 = t4.*3.92423e-1;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
H = reshape([0.0,0.0,0.0,t2.*t7.*(9.81e+2./1.0e+2),t4.*t6.*(-9.81e+2./1.0e+2)+t2.*t3.*t5.*(9.81e+2./1.0e+2),t3.*t4.*(-9.81e+2./1.0e+2)-t2.*t5.*t6.*(9.81e+2./1.0e+2),t7.*t13,-t4.*(t6.*3.92423e-1-t3.*t5.*1.0851e-2)+t6.*t8+t3.*t5.*t10,t3.*t14-t5.*t6.*t13,0.0,0.0,0.0,t4.*t5.*(9.81e+2./1.0e+2)-t7.*xdotdot+t5.*ydotdot,t3.*t4.*t7.*(-9.81e+2./1.0e+2)-t3.*t5.*xdotdot-t3.*t7.*ydotdot,t4.*t6.*t7.*(9.81e+2./1.0e+2)+t5.*t6.*xdotdot+t6.*t7.*ydotdot,t7.*(-2.38836e-1)-t5.*t14,t3.*t5.*(-2.38836e-1)-t3.*t4.*t7.*3.92423e-1+t3.*t7.*t8,t5.*t6.*2.38836e-1-t6.*t7.*t14,0.0,t3.*thetadot,-t6.*thetadot,0.0,t2.*t3.*(9.81e+2./1.0e+2)-t4.*t5.*t6.*(9.81e+2./1.0e+2)+t6.*t7.*xdotdot-t5.*t6.*ydotdot,t2.*t6.*(-9.81e+2./1.0e+2)-t3.*t4.*t5.*(9.81e+2./1.0e+2)+t3.*t7.*xdotdot-t3.*t5.*ydotdot,0.0,t2.*(t3.*3.92423e-1+t5.*t6.*1.0851e-2)+t3.*t9+t6.*t7.*2.38836e-1-t4.*t5.*t6.*3.92423e-1,t3.*t7.*2.38836e-1-t6.*t13+t3.*t5.*t14,0.0,t6,t3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5,-t3.*t7,t6.*t7,0.0,0.0,0.0,0.0,0.0,0.0,t7,t3.*t5,-t5.*t6,0.0,0.0,0.0],[9,7]);
