function B = B_dynamic_matrix(phi,theta)
%B_DYNAMIC_MATRIX
%    B = B_DYNAMIC_MATRIX(PHI,THETA)
% Robotics project, Menolotto Mariangela & Stefano Maugeri
%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Dec-2021 13:21:13

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
t10 = t2.*t3.*1.0544538e+1;
t11 = t2.*t5.*1.0544538e+1;
t12 = t3.*t4.*1.0544538e+1;
t13 = t4.*t5.*1.0544538e+1;
t14 = -t10;
B = reshape([3.1022e+1,0.0,t12,t11,0.0,0.0,0.0,3.1022e+1,t13,t14,0.0,0.0,t12,t13,t6.*2.2642e-1+t7.*1.968128e-1+t8.*1.86642+t9.*1.968128e-1+t7.*t8.*3.996379902+t8.*t9.*3.996379902,0.0,0.0,0.0,t11,t14,0.0,t8.*3.996379902+t6.*t7.*3.996379902+t6.*t9.*3.996379902+1.7106,5.3e-3,5.3e-3,0.0,0.0,0.0,5.3e-3,5.3e-3,0.0,0.0,0.0,0.0,5.3e-3,0.0,5.3e-3],[6,6]);
