function C = C_dynamic_matrix(phi,phidot,theta,thetadot)
%C_DYNAMIC_MATRIX
%    C = C_DYNAMIC_MATRIX(PHI,PHIDOT,THETA,THETADOT)
% Robotics project, Menolotto Mariangela & Stefano Maugeri
%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Dec-2021 13:21:13

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = t3.^2;
t7 = t5.^2;
t8 = t2.*t4.*(4.1e+1./2.5e+1);
t9 = t2.*t4.*t6.*3.996379902;
t10 = t2.*t4.*t7.*3.996379902;
t11 = t8+t9+t10;
t12 = t11.*thetadot;
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,phidot.*t2.*t3.*1.0544538e+1-t4.*t5.*thetadot.*1.0544538e+1,phidot.*t2.*t5.*1.0544538e+1+t3.*t4.*thetadot.*1.0544538e+1,phidot.*t11,-t12,0.0,0.0,phidot.*t4.*t5.*(-1.0544538e+1)+t2.*t3.*thetadot.*1.0544538e+1,phidot.*t3.*t4.*1.0544538e+1+t2.*t5.*thetadot.*1.0544538e+1,t12,-phidot.*(t9+t10-t2.*t4.*3.996379902),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
