function G = G_dynamic_vector(alpha,phi,theta)
%G_DYNAMIC_VECTOR
%    G = G_DYNAMIC_VECTOR(ALPHA,PHI,THETA)
% Robotics project, Menolotto Mariangela & Stefano Maugeri
%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Dec-2021 13:21:14

t2 = sin(alpha);
t3 = sin(phi);
G = [0.0;t2.*3.0432582e+2;t2.*t3.*sin(theta).*1.0344191778e+2;t3.*cos(alpha).*(-1.0344191778e+2)-t2.*cos(phi).*cos(theta).*1.0344191778e+2;0.0;0.0];
